// Code generated by goctl. DO NOT EDIT.
// Source: training.proto

package shoptraining

import (
	"context"

	"yufuture-gpt/app/training/cmd/rpc/pb/training"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	KnowledgeBaseTrainingReq  = training.KnowledgeBaseTrainingReq
	KnowledgeBaseTrainingResp = training.KnowledgeBaseTrainingResp
	ShopTrainingReq           = training.ShopTrainingReq
	ShopTrainingResp          = training.ShopTrainingResp

	ShopTraining interface {
		PreSetting(ctx context.Context, in *ShopTrainingReq, opts ...grpc.CallOption) (*ShopTrainingResp, error)
	}

	defaultShopTraining struct {
		cli zrpc.Client
	}
)

func NewShopTraining(cli zrpc.Client) ShopTraining {
	return &defaultShopTraining{
		cli: cli,
	}
}

func (m *defaultShopTraining) PreSetting(ctx context.Context, in *ShopTrainingReq, opts ...grpc.CallOption) (*ShopTrainingResp, error) {
	client := training.NewShopTrainingClient(m.cli.Conn())
	return client.PreSetting(ctx, in, opts...)
}
