// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	JWT "yufuture-gpt/app/training/cmd/api/internal/handler/JWT"
	basicFunction "yufuture-gpt/app/training/cmd/api/internal/handler/basicFunction"
	shopTraining "yufuture-gpt/app/training/cmd/api/internal/handler/shopTraining"
	"yufuture-gpt/app/training/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getJWT",
				Handler: JWT.GetJWTHandler(serverCtx),
			},
		},
		rest.WithPrefix("/JWT"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getDictInfoByType",
				Handler: basicFunction.GetDictInfoByTypeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/basicFunction"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/enableGoods",
				Handler: shopTraining.EnableGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getGoodsPageList",
				Handler: shopTraining.GetGoodsPageListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getShopPageList",
				Handler: shopTraining.GetShopPageListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/preSetting",
				Handler: shopTraining.PreSettingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trainingGoods",
				Handler: shopTraining.TrainingGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trainingShop",
				Handler: shopTraining.TrainingShopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unEnableGoods",
				Handler: shopTraining.UnEnableGoodsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/shopTraining"),
	)
}
