// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"yufuture-gpt/app/user/cmd/rpc/internal/logic/user"
	"yufuture-gpt/app/user/cmd/rpc/internal/svc"
	"yufuture-gpt/app/user/cmd/rpc/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 获取当前登录用户数据
func (s *UserServer) GetCurrentUserData(ctx context.Context, in *user.CurrentUserDataReq) (*user.CurrentUserDataResp, error) {
	l := userlogic.NewGetCurrentUserDataLogic(ctx, s.svcCtx)
	return l.GetCurrentUserData(in)
}

// 绑定手机号
func (s *UserServer) BindPhone(ctx context.Context, in *user.BindPhoneReq) (*user.BindPhoneResp, error) {
	l := userlogic.NewBindPhoneLogic(ctx, s.svcCtx)
	return l.BindPhone(in)
}
