// Code generated by goctl. DO NOT EDIT.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tsShopLogFieldNames          = builder.RawFieldNames(&TsShopLog{})
	tsShopLogRows                = strings.Join(tsShopLogFieldNames, ",")
	tsShopLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tsShopLogFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tsShopLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tsShopLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tsShopLogModel interface {
		Insert(ctx context.Context, data *TsShopLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TsShopLog, error)
		Update(ctx context.Context, data *TsShopLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTsShopLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TsShopLog struct {
		Id             int64     `db:"id"`              // 店铺训练ID
		ShopId         int64     `db:"shop_id"`         // 店铺ID
		TrainingResult int64     `db:"training_result"` // 训练结果 0: 未知 1: 成功 2: 失败 3: 部分成功
		Token          int64     `db:"token"`           // 消耗的token
		Power          int64     `db:"power"`           // 消耗的算力
		StartTime      time.Time `db:"start_time"`      // 开始时间
		EndTime        time.Time `db:"end_time"`        // 结束时间
		CreateTime     time.Time `db:"create_time"`     // 创建时间
		UpdateTime     time.Time `db:"update_time"`     // 修改时间
		CreateBy       int64     `db:"create_by"`       // 创建人
		UpdateBy       int64     `db:"update_by"`       // 修改人
	}
)

func newTsShopLogModel(conn sqlx.SqlConn) *defaultTsShopLogModel {
	return &defaultTsShopLogModel{
		conn:  conn,
		table: "`ts_shop_log`",
	}
}

func (m *defaultTsShopLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTsShopLogModel) FindOne(ctx context.Context, id int64) (*TsShopLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tsShopLogRows, m.table)
	var resp TsShopLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTsShopLogModel) Insert(ctx context.Context, data *TsShopLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tsShopLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ShopId, data.TrainingResult, data.Token, data.Power, data.StartTime, data.EndTime, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultTsShopLogModel) Update(ctx context.Context, data *TsShopLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tsShopLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ShopId, data.TrainingResult, data.Token, data.Power, data.StartTime, data.EndTime, data.CreateBy, data.UpdateBy, data.Id)
	return err
}

func (m *defaultTsShopLogModel) tableName() string {
	return m.table
}
