Name: training.rpc
ListenOn: 0.0.0.0:7052
#Etcd:
#  Hosts:
#  - 127.0.0.1:2379
#  Key: training.rpc

Consul:
  Host: 192.168.3.118:8500 # consul endpoint
  #Token: 'f0512db6-76d6-f25e-f344-a98cc3484d42' # consul ACL token (optional)
  Key: training.rpc # service name registered to Consul
  Meta:
    Protocol: grpc
  Tag:
    - tag
    - rpc

DB:
  DataSource: root:mysql_QspKnh@tcp(192.168.3.118:3306)/qyfuture_gpt?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
Mongo:
  Url: mongodb://mongo_kKtPGm:mongo_tmPizQ@192.168.3.118:27017
  Database: kefugpt
  Kfgptaccountsentities: kfgptaccountsentities