Name: training.rpc
ListenOn: 0.0.0.0:7052
#Etcd:
#  Hosts:
#  - 127.0.0.1:2379
#  Key: training.rpc

Consul:
  Host: 192.168.3.118:8500
  #Token: 'f0512db6-76d6-f25e-f344-a98cc3484d42' # consul ACL token (optional)
  Key: training.rpc
  Meta:
    Protocol: grpc
  Tag:
    - tag
    - rpc

DB:
  DataSource: root:mysql_QspKnh@tcp(192.168.3.118:3306)/qyfuture_gpt?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

Mongo:
  Url: mongodb://mongo_kKtPGm:mongo_tmPizQ@192.168.3.118:27017
  Database: kefugpt
  Kfgptaccountsentities: kfgptaccountsentities

KqPusherConf:
  Brokers:
    - 192.168.3.118:9092
  Topic: training-goods

KqConsumerConf:
  Name: trainingGoodsConsumer
  Brokers:
    - 192.168.3.118:9092
  Group: trainingGoodsConsumer
  Topic: training-goods
  Offset: first
  Consumers: 8
  Processors: 8

Elasticsearch:
  Addresses:
    - http://192.168.3.118:9200
  Username: elastic
  Password: Elastic_HMYzHB

#雪花算法节点ID 每个节点的值不能一样
SnowFlakeNode: 1

TrainingGoodsConf:
  #商品训练队列消费者的延迟时间，默认10秒
  ConsumeDelay: 10000
  #gpt图片生成文字地址
  GptImageURL: http://192.168.3.200:8447/chat_with_openai_image

