// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "yufuture-gpt/app/user/cmd/api/internal/handler/login"
	"yufuture-gpt/app/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取图像验证码
				Method:  http.MethodGet,
				Path:    "/getCaptcha",
				Handler: login.GetCaptchaHandler(serverCtx),
			},
			{
				// 获取手机短信验证码
				Method:  http.MethodPost,
				Path:    "/getVerificationCode",
				Handler: login.GetVerificationCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/login"),
	)
}
