// Code generated by goctl. DO NOT EDIT.
// Source: training.proto

package server

import (
	"context"

	"yufuture-gpt/app/training/cmd/rpc/internal/logic/basicfunction"
	"yufuture-gpt/app/training/cmd/rpc/internal/svc"
	"yufuture-gpt/app/training/cmd/rpc/pb/training"
)

type BasicFunctionServer struct {
	svcCtx *svc.ServiceContext
	training.UnimplementedBasicFunctionServer
}

func NewBasicFunctionServer(svcCtx *svc.ServiceContext) *BasicFunctionServer {
	return &BasicFunctionServer{
		svcCtx: svcCtx,
	}
}

func (s *BasicFunctionServer) GetDictInfoByType(ctx context.Context, in *training.DictInfoByTypeReq) (*training.DictInfoByTypeResp, error) {
	l := basicfunctionlogic.NewGetDictInfoByTypeLogic(ctx, s.svcCtx)
	return l.GetDictInfoByType(in)
}
