// Code generated by goctl. DO NOT EDIT.
// Source: training.proto

package server

import (
	"context"

	"yufuture-gpt/app/training/cmd/rpc/internal/logic/shoptraining"
	"yufuture-gpt/app/training/cmd/rpc/internal/svc"
	"yufuture-gpt/app/training/cmd/rpc/pb/training"
)

type ShopTrainingServer struct {
	svcCtx *svc.ServiceContext
	training.UnimplementedShopTrainingServer
}

func NewShopTrainingServer(svcCtx *svc.ServiceContext) *ShopTrainingServer {
	return &ShopTrainingServer{
		svcCtx: svcCtx,
	}
}

func (s *ShopTrainingServer) PreSetting(ctx context.Context, in *training.ShopTrainingReq) (*training.ShopTrainingResp, error) {
	l := shoptraininglogic.NewPreSettingLogic(ctx, s.svcCtx)
	return l.PreSetting(in)
}
