// Code generated by goctl. DO NOT EDIT.
package types

type BaseReq struct {
}

type BaseResp struct {
	Code int
	Msg  string
}

type ShopTrainingReq struct {
}

type ShopTrainingResp struct {
	BaseResp
	Data interface{}
}
