// Code generated by goctl. DO NOT EDIT.
package types

type AddGoodsReq struct {
	ShopId string   `json:"shopId"` // 店铺id
	List   []string `json:"list"`   // 商品url列表
}

type BaseGoodsReq struct {
	GoodsId string `json:"goodsId"` // 商品id
}

type BasePageReq struct {
	PageNum  int64  `json:"pageNum"`  // 页码
	PageSize int64  `json:"pageSize"` // 每页条数
	Query    string `json:"query"`    // 查询条件
}

type BasePageResp struct {
	PageNum  int64 `json:"pageNum"`  // 页码
	PageSize int64 `json:"pageSize"` // 每页条数
	Total    int64 `json:"total"`    // 总条数
}

type BaseReq struct {
}

type BaseResp struct {
	Code int    `json:"code"` // 状态码
	Msg  string `json:"msg"`  // 信息
}

type CancelPreSettingGoodsReq struct {
	GoodsId string `json:"goodsId"` // 商品id
}

type CancelPreSettingReq struct {
	Uuid string `json:"uuid"` // 唯一标识
}

type DictInfo struct {
	Name     string `json:"name"`     // 名称
	Value    string `json:"value"`    // 值
	OrderNum int64  `json:"orderNum"` // 排序
}

type DictInfoByTypeReq struct {
	Key string `json:"key"` // 类型key
}

type DictInfoByTypeResp struct {
	BaseResp
	Data []*DictInfo `json:"data"` // 字典列表
}

type GetGoodsTrainingProgressReq struct {
	GoodsId string `json:"goodsId"` // 商品id
}

type GetGoodsTrainingProgressResp struct {
	BaseResp
	Data interface{} `json:"data"` // 训练进度
}

type GetGoodsTrainingResultReq struct {
	GoodsId string `json:"goodsId"` // 商品id
}

type GetGoodsTrainingResultResp struct {
	BaseResp
	Data interface{} `json:"data"` // 训练结果
}

type GetShopTrainingProgressReq struct {
	Uuid string `json:"uuid"` // 唯一标识
}

type GetShopTrainingProgressResp struct {
	BaseResp
	Data interface{} `json:"data"` // 训练进度
}

type GoodsListResp struct {
	BasePageResp
	List []*GoodsResp `json:"list"` // 列表
}

type GoodsPageListReq struct {
	BasePageReq
	ShopId     string `json:"shopId"`     // 店铺id
	Enabled    int64  `json:"enabled"`    // 启用状态  0: 未定义 1: 未启用 2: 启用
	UpdateTime int64  `json:"updateTime"` // 更新时间
}

type GoodsPageListResp struct {
	BaseResp
	Data *GoodsListResp `json:"data"` // 数据
}

type GoodsResp struct {
	Id              string `json:"id"`              // 商品id
	ShopId          string `json:"shopId"`          // 店铺id
	GoodsName       string `json:"goodsName"`       // 商品名称
	GoodsUrl        string `json:"goodsUrl"`        // 商品url
	TrainingSummary string `json:"trainingSummary"` // 训练摘要
	Enabled         int64  `json:"enabled"`         // 启用状态 0: 未定义 1: 未启用 2: 启用
	TrainingStatus  int64  `json:"trainStatus"`     // 训练状态 训练状态 0: 未训练 1: 训练中 2: 训练完成
	TrainingTimes   int64  `json:"trainingTimes"`   // 训练次数
	UpdateTime      int64  `json:"updateTime"`      // 更新时间
}

type JudgeFirstShopReq struct {
	Uuid string `json:"uuid"` // 唯一标识
}

type JudgeFirstShopResp struct {
	BaseResp
	Data int64 `json:"data"` // 是否初次 0: 是 1: 否
}

type PreSettingGoodsReq struct {
	GoodsId string `json:"goodsId"` // 商品id
}

type SaveGoods struct {
	GoodsName  string `json:"name"`
	GoodsUrl   string `json:"url"`
	PlatFormId string `json:"id"`
}

type SaveShopReq struct {
	SerialNumber string      `json:"serial_number"`
	Uuid         string      `json:"uuid"`
	ShopName     string      `json:"shop_name"`
	PlatForm     string      `json:"platform"`
	GoodsList    []SaveGoods `json:"goods_list"`
}

type SaveShopResp struct {
	BaseResp
}

type ShopListResp struct {
	BasePageResp
	List []*ShopResp `json:"list"` // 列表
}

type ShopPageListReq struct {
	BasePageReq
	PlatFormType   int64 `json:"platFormType"` // 平台类型
	TrainingStatus int64 `json:"trainStatus"`  // 训练状态
	UpdateTime     int64 `json:"updateTime"`   // 更新时间
}

type ShopPageListResp struct {
	BaseResp
	Data *ShopListResp `json:"data"` // 数据
}

type ShopResp struct {
	Id             string `json:"id"`           // 店铺id
	Uuid           string `json:"uuid"`         // 唯一标识
	ShopName       string `json:"shopName"`     // 店铺名称
	PlatFormType   int64  `json:"platFormType"` // 平台类型
	TrainingStatus int64  `json:"trainStatus"`  // 训练状态
	TrainingTimes  int64  `json:"trainTimes"`   // 训练次数
	UpdateTime     int64  `json:"updateTime"`   // 更新时间
}

type ShopTrainingReq struct {
	Uuid         string `json:"uuid"`         // 唯一标识
	PlatFormType int64  `json:"platFormType"` // 平台类型
	ShopName     string `json:"shopName"`
	Cookies      string `json:"cookies"`
}

type ShopTrainingResp struct {
	BaseResp
	Data interface{} `json:"data"` // 数据
}

type TrainingGoodsReq struct {
	GoodsId string `json:"goodsId"` // 商品id
}

type TrainingGoodsResp struct {
	BaseResp
	Data int64 `json:"data"` // 训练状态 0: 未训练 1: 训练中 2: 训练完成
}

type TrainingShopReq struct {
	Uuid string `json:"uuid"` // 唯一标识
}

type TrainingShopResp struct {
	BaseResp
	Data int64 `json:"data"` // 训练状态 0: 未训练 1: 训练中 2: 训练完成
}
