// Code generated by goctl. DO NOT EDIT.
// Source: training.proto

package knowledgebasetraining

import (
	"context"

	"yufuture-gpt/app/training/cmd/rpc/pb/training"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DictInfo                  = training.DictInfo
	DictInfoByTypeReq         = training.DictInfoByTypeReq
	DictInfoByTypeResp        = training.DictInfoByTypeResp
	KnowledgeBaseTrainingReq  = training.KnowledgeBaseTrainingReq
	KnowledgeBaseTrainingResp = training.KnowledgeBaseTrainingResp
	ShopTrainingReq           = training.ShopTrainingReq
	ShopTrainingResp          = training.ShopTrainingResp

	KnowledgeBaseTraining interface {
		PreSetting(ctx context.Context, in *KnowledgeBaseTrainingReq, opts ...grpc.CallOption) (*KnowledgeBaseTrainingResp, error)
	}

	defaultKnowledgeBaseTraining struct {
		cli zrpc.Client
	}
)

func NewKnowledgeBaseTraining(cli zrpc.Client) KnowledgeBaseTraining {
	return &defaultKnowledgeBaseTraining{
		cli: cli,
	}
}

func (m *defaultKnowledgeBaseTraining) PreSetting(ctx context.Context, in *KnowledgeBaseTrainingReq, opts ...grpc.CallOption) (*KnowledgeBaseTrainingResp, error) {
	client := training.NewKnowledgeBaseTrainingClient(m.cli.Conn())
	return client.PreSetting(ctx, in, opts...)
}
