// Code generated by goctl. DO NOT EDIT.
// Source: training.proto

package knowledgebasetraining

import (
	"context"

	"yufuture-gpt/app/training/cmd/rpc/pb/training"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGoodsReq                  = training.AddGoodsReq
	AddGoodsResp                 = training.AddGoodsResp
	CancelPreSettingReq          = training.CancelPreSettingReq
	DictInfo                     = training.DictInfo
	DictInfoByTypeReq            = training.DictInfoByTypeReq
	DictInfoByTypeResp           = training.DictInfoByTypeResp
	GetGoodsTrainingProgressReq  = training.GetGoodsTrainingProgressReq
	GetGoodsTrainingProgressResp = training.GetGoodsTrainingProgressResp
	GetGoodsTrainingResultReq    = training.GetGoodsTrainingResultReq
	GetGoodsTrainingResultResp   = training.GetGoodsTrainingResultResp
	GetShopTrainingProgressReq   = training.GetShopTrainingProgressReq
	GetShopTrainingProgressResp  = training.GetShopTrainingProgressResp
	GoodsPageListReq             = training.GoodsPageListReq
	GoodsPageListResp            = training.GoodsPageListResp
	GoodsResp                    = training.GoodsResp
	GoodsTrainingReq             = training.GoodsTrainingReq
	GoodsTrainingResp            = training.GoodsTrainingResp
	JudgeFirstShopReq            = training.JudgeFirstShopReq
	JudgeFirstShopResp           = training.JudgeFirstShopResp
	KnowledgeBaseTrainingReq     = training.KnowledgeBaseTrainingReq
	KnowledgeBaseTrainingResp    = training.KnowledgeBaseTrainingResp
	SaveGoods                    = training.SaveGoods
	SaveShopReq                  = training.SaveShopReq
	SaveShopResp                 = training.SaveShopResp
	ShopPageListReq              = training.ShopPageListReq
	ShopPageListResp             = training.ShopPageListResp
	ShopResp                     = training.ShopResp
	ShopTrainingReq              = training.ShopTrainingReq
	ShopTrainingResp             = training.ShopTrainingResp
	TrainingGoodsReq             = training.TrainingGoodsReq
	TrainingGoodsResp            = training.TrainingGoodsResp
	TrainingShopReq              = training.TrainingShopReq
	TrainingShopResp             = training.TrainingShopResp

	KnowledgeBaseTraining interface {
		PreSetting(ctx context.Context, in *KnowledgeBaseTrainingReq, opts ...grpc.CallOption) (*KnowledgeBaseTrainingResp, error)
	}

	defaultKnowledgeBaseTraining struct {
		cli zrpc.Client
	}
)

func NewKnowledgeBaseTraining(cli zrpc.Client) KnowledgeBaseTraining {
	return &defaultKnowledgeBaseTraining{
		cli: cli,
	}
}

func (m *defaultKnowledgeBaseTraining) PreSetting(ctx context.Context, in *KnowledgeBaseTrainingReq, opts ...grpc.CallOption) (*KnowledgeBaseTrainingResp, error) {
	client := training.NewKnowledgeBaseTrainingClient(m.cli.Conn())
	return client.PreSetting(ctx, in, opts...)
}
