// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package login

import (
	"context"

	"yufuture-gpt/app/user/cmd/rpc/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegisterReq  = user.RegisterReq
	RegisterResp = user.RegisterResp
	UserInfo     = user.UserInfo

	Login interface {
		// 注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

// 注册
func (m *defaultLogin) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}
