// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package login

import (
	"context"

	"yufuture-gpt/app/user/cmd/rpc/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BindPhoneReq        = user.BindPhoneReq
	BindPhoneResp       = user.BindPhoneResp
	ChangeOrgReq        = user.ChangeOrgReq
	ChangeOrgResp       = user.ChangeOrgResp
	CurrentUserData     = user.CurrentUserData
	CurrentUserDataReq  = user.CurrentUserDataReq
	CurrentUserDataResp = user.CurrentUserDataResp
	LoginReq            = user.LoginReq
	LoginResp           = user.LoginResp
	MessageInfo         = user.MessageInfo
	MessageListReq      = user.MessageListReq
	MessageListResp     = user.MessageListResp
	OrgInfo             = user.OrgInfo
	OrgListReq          = user.OrgListReq
	OrgListResp         = user.OrgListResp
	RegisterReq         = user.RegisterReq
	RegisterResp        = user.RegisterResp
	UpdateHeadImgReq    = user.UpdateHeadImgReq
	UpdateHeadImgResp   = user.UpdateHeadImgResp
	UpdateNickNameReq   = user.UpdateNickNameReq
	UpdateNickNameResp  = user.UpdateNickNameResp
	UpdateOrgNameReq    = user.UpdateOrgNameReq
	UpdateOrgNameResp   = user.UpdateOrgNameResp
	UserInfo            = user.UserInfo
	WechatUserInfoReq   = user.WechatUserInfoReq
	WechatUserInfoResp  = user.WechatUserInfoResp

	Login interface {
		// 注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// 登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 获取微信用户信息
		GetWechatUserInfo(ctx context.Context, in *WechatUserInfoReq, opts ...grpc.CallOption) (*WechatUserInfoResp, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

// 注册
func (m *defaultLogin) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 登录
func (m *defaultLogin) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取微信用户信息
func (m *defaultLogin) GetWechatUserInfo(ctx context.Context, in *WechatUserInfoReq, opts ...grpc.CallOption) (*WechatUserInfoResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.GetWechatUserInfo(ctx, in, opts...)
}
