// Code generated by goctl. DO NOT EDIT.
package types

type BasePageReq struct {
	PageNum  int64  `json:"pageNum"`  // 页码
	PageSize int64  `json:"pageSize"` // 每页条数
	Query    string `json:"query"`    // 查询条件
}

type BasePageResp struct {
	PageNum  int64 `json:"pageNum"`  // 页码
	PageSize int64 `json:"pageSize"` // 每页条数
	Total    int64 `json:"total"`    // 总条数
}

type BaseReq struct {
}

type BaseResp struct {
	Code int    `json:"code"` // 状态码
	Msg  string `json:"msg"`  // 信息
}

type CaptchaData struct {
	CaptchaId  string `json:"captchaId"`  // 验证码ID
	CaptchaImg string `json:"captchaImg"` // 验证码图片
}

type CaptchaResp struct {
	BaseResp
	Data CaptchaData `json:"data"` // 图形验证码信息
}

type DictInfo struct {
	Name     string `json:"name"`     // 名称
	Value    string `json:"value"`    // 值
	OrderNum int64  `json:"orderNum"` // 排序
}

type DictInfoByTypeReq struct {
	Key string `json:"key"` // 类型key
}

type DictInfoByTypeResp struct {
	BaseResp
	Data []*DictInfo `json:"data"` // 字典列表
}
