// Code generated by goctl. DO NOT EDIT.
package types

type BasePageReq struct {
	PageNum  int64  `json:"pageNum"`  // 页码
	PageSize int64  `json:"pageSize"` // 每页条数
	Query    string `json:"query"`    // 查询条件
}

type BasePageResp struct {
	PageNum  int64 `json:"pageNum"`  // 页码
	PageSize int64 `json:"pageSize"` // 每页条数
	Total    int64 `json:"total"`    // 总条数
}

type BaseReq struct {
}

type BaseResp struct {
	Code int    `json:"code"` // 状态码
	Msg  string `json:"msg"`  // 信息
}

type CaptchaData struct {
	CaptchaId  string `json:"captchaId"`  // 验证码ID
	CaptchaImg string `json:"captchaImg"` // 验证码图片
}

type CaptchaResp struct {
	BaseResp
	Data CaptchaData `json:"data"` // 图形验证码信息
}

type DictInfo struct {
	Name     string `json:"name"`     // 名称
	Value    string `json:"value"`    // 值
	OrderNum int64  `json:"orderNum"` // 排序
}

type DictInfoByTypeReq struct {
	Key string `json:"key"` // 类型key
}

type DictInfoByTypeResp struct {
	BaseResp
	Data []*DictInfo `json:"data"` // 字典列表
}

type LoginQrCodeData struct {
	TicketQrCodeUrl string `json:"ticketQrCodeUrl"`
	Ticket          string `json:"ticket"`
}

type LoginQrCodeResp struct {
	BaseResp
	Data LoginQrCodeData `json:"data"`
}

type LoginReq struct {
	Phone            string `json:"phone"`            // 手机号码
	VerificationCode string `json:"verificationCode"` // 手机验证码
	CaptchaId        string `json:"captchaId"`        // 验证码ID
	Answer           string `json:"answer"`           // 验证码答案
}

type LoginResp struct {
	BaseResp
	Data UserInfo `json:"data"` // 用户信息
}

type RegisterReq struct {
	Phone            string `json:"phone"`            // 手机号码
	VerificationCode string `json:"verificationCode"` // 手机验证码
	CaptchaId        string `json:"captchaId"`        // 验证码ID
	Answer           string `json:"answer"`           // 验证码答案
}

type RegisterResp struct {
	BaseResp
	Data UserInfo `json:"data"` // 用户信息
}

type UserInfo struct {
	Token    string `json:"token"`    // JWT Token
	Phone    string `json:"phone"`    // 手机号码
	NickName string `json:"nickname"` // 昵称
	HeadImg  string `json:"headImg"`  // 头像
}

type VerificationCodeReq struct {
	Phone string `json:"phone"` // 手机号码
}
