// Code generated by goctl. DO NOT EDIT.
// Source: org.proto

package server

import (
	"context"

	"yufuture-gpt/app/user/cmd/rpc/internal/logic/org"
	"yufuture-gpt/app/user/cmd/rpc/internal/svc"
	"yufuture-gpt/app/user/cmd/rpc/pb/user"
)

type OrgServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedOrgServer
}

func NewOrgServer(svcCtx *svc.ServiceContext) *OrgServer {
	return &OrgServer{
		svcCtx: svcCtx,
	}
}

// 查找团队
func (s *OrgServer) SearchOrg(ctx context.Context, in *user.SearchOrgReq) (*user.SearchOrgReqResp, error) {
	l := orglogic.NewSearchOrgLogic(ctx, s.svcCtx)
	return l.SearchOrg(in)
}

// 查找用户
func (s *OrgServer) SearchUser(ctx context.Context, in *user.SearchUserReq) (*user.SearchUserResp, error) {
	l := orglogic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}
