// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: pb/org.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查找团队请求体
type SearchOrgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchOrgReq) Reset() {
	*x = SearchOrgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchOrgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrgReq) ProtoMessage() {}

func (x *SearchOrgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrgReq.ProtoReflect.Descriptor instead.
func (*SearchOrgReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{0}
}

func (x *SearchOrgReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// 查找团队返回体
type SearchOrgReqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result []*SearchOrgInfo `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *SearchOrgReqResp) Reset() {
	*x = SearchOrgReqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchOrgReqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrgReqResp) ProtoMessage() {}

func (x *SearchOrgReqResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrgReqResp.ProtoReflect.Descriptor instead.
func (*SearchOrgReqResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{1}
}

func (x *SearchOrgReqResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchOrgReqResp) GetResult() []*SearchOrgInfo {
	if x != nil {
		return x.Result
	}
	return nil
}

// 查找团队信息
type SearchOrgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId   int64  `protobuf:"varint,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	OrgName string `protobuf:"bytes,2,opt,name=orgName,proto3" json:"orgName,omitempty"`
}

func (x *SearchOrgInfo) Reset() {
	*x = SearchOrgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchOrgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrgInfo) ProtoMessage() {}

func (x *SearchOrgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrgInfo.ProtoReflect.Descriptor instead.
func (*SearchOrgInfo) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{2}
}

func (x *SearchOrgInfo) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SearchOrgInfo) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

// 查找用户请求体
type SearchUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchUserReq) Reset() {
	*x = SearchUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserReq) ProtoMessage() {}

func (x *SearchUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserReq.ProtoReflect.Descriptor instead.
func (*SearchUserReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{3}
}

func (x *SearchUserReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// 查找用户返回体
type SearchUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result []*SearchUserInfo `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *SearchUserResp) Reset() {
	*x = SearchUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResp) ProtoMessage() {}

func (x *SearchUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResp.ProtoReflect.Descriptor instead.
func (*SearchUserResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUserResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchUserResp) GetResult() []*SearchUserInfo {
	if x != nil {
		return x.Result
	}
	return nil
}

// 查找用户信息
type SearchUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Phone  string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *SearchUserInfo) Reset() {
	*x = SearchUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserInfo) ProtoMessage() {}

func (x *SearchUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserInfo.ProtoReflect.Descriptor instead.
func (*SearchUserInfo) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{5}
}

func (x *SearchUserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchUserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 用户申请加入团队请求体
type ApplyJoinOrgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrgId  int64 `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
}

func (x *ApplyJoinOrgReq) Reset() {
	*x = ApplyJoinOrgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyJoinOrgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyJoinOrgReq) ProtoMessage() {}

func (x *ApplyJoinOrgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyJoinOrgReq.ProtoReflect.Descriptor instead.
func (*ApplyJoinOrgReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyJoinOrgReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyJoinOrgReq) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

// 用户申请加入团队返回体
type ApplyJoinOrgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ApplyJoinOrgResp) Reset() {
	*x = ApplyJoinOrgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyJoinOrgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyJoinOrgResp) ProtoMessage() {}

func (x *ApplyJoinOrgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyJoinOrgResp.ProtoReflect.Descriptor instead.
func (*ApplyJoinOrgResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyJoinOrgResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 邀请用户加入团队请求体
type InviteJoinOrgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	InviteUserId int64 `protobuf:"varint,2,opt,name=inviteUserId,proto3" json:"inviteUserId,omitempty"`
}

func (x *InviteJoinOrgReq) Reset() {
	*x = InviteJoinOrgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteJoinOrgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteJoinOrgReq) ProtoMessage() {}

func (x *InviteJoinOrgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteJoinOrgReq.ProtoReflect.Descriptor instead.
func (*InviteJoinOrgReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{8}
}

func (x *InviteJoinOrgReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InviteJoinOrgReq) GetInviteUserId() int64 {
	if x != nil {
		return x.InviteUserId
	}
	return 0
}

// 邀请用户加入团队返回体
type InviteJoinOrgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *InviteJoinOrgResp) Reset() {
	*x = InviteJoinOrgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteJoinOrgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteJoinOrgResp) ProtoMessage() {}

func (x *InviteJoinOrgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteJoinOrgResp.ProtoReflect.Descriptor instead.
func (*InviteJoinOrgResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{9}
}

func (x *InviteJoinOrgResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 同意用户申请加入团队请求体
type AgreeApplyJoinOrgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MessageId int64 `protobuf:"varint,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
}

func (x *AgreeApplyJoinOrgReq) Reset() {
	*x = AgreeApplyJoinOrgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgreeApplyJoinOrgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreeApplyJoinOrgReq) ProtoMessage() {}

func (x *AgreeApplyJoinOrgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreeApplyJoinOrgReq.ProtoReflect.Descriptor instead.
func (*AgreeApplyJoinOrgReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{10}
}

func (x *AgreeApplyJoinOrgReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AgreeApplyJoinOrgReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// 同意用户申请加入团队返回体
type AgreeApplyJoinOrgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AgreeApplyJoinOrgResp) Reset() {
	*x = AgreeApplyJoinOrgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgreeApplyJoinOrgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreeApplyJoinOrgResp) ProtoMessage() {}

func (x *AgreeApplyJoinOrgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreeApplyJoinOrgResp.ProtoReflect.Descriptor instead.
func (*AgreeApplyJoinOrgResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{11}
}

func (x *AgreeApplyJoinOrgResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 同意用户邀请加入团队请求体
type AgreeInviteJoinOrgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MessageId int64 `protobuf:"varint,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
}

func (x *AgreeInviteJoinOrgReq) Reset() {
	*x = AgreeInviteJoinOrgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgreeInviteJoinOrgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreeInviteJoinOrgReq) ProtoMessage() {}

func (x *AgreeInviteJoinOrgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreeInviteJoinOrgReq.ProtoReflect.Descriptor instead.
func (*AgreeInviteJoinOrgReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{12}
}

func (x *AgreeInviteJoinOrgReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AgreeInviteJoinOrgReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// 同意用户邀请加入团队返回体
type AgreeInviteJoinOrgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AgreeInviteJoinOrgResp) Reset() {
	*x = AgreeInviteJoinOrgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgreeInviteJoinOrgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreeInviteJoinOrgResp) ProtoMessage() {}

func (x *AgreeInviteJoinOrgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreeInviteJoinOrgResp.ProtoReflect.Descriptor instead.
func (*AgreeInviteJoinOrgResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{13}
}

func (x *AgreeInviteJoinOrgResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 获取团队角色列表请求体
type OrgRoleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Query  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *OrgRoleListReq) Reset() {
	*x = OrgRoleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgRoleListReq) ProtoMessage() {}

func (x *OrgRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgRoleListReq.ProtoReflect.Descriptor instead.
func (*OrgRoleListReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{14}
}

func (x *OrgRoleListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrgRoleListReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// 获取团队角色列表返回体
type OrgRoleListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result []*OrgRole `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *OrgRoleListResp) Reset() {
	*x = OrgRoleListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgRoleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgRoleListResp) ProtoMessage() {}

func (x *OrgRoleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgRoleListResp.ProtoReflect.Descriptor instead.
func (*OrgRoleListResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{15}
}

func (x *OrgRoleListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrgRoleListResp) GetResult() []*OrgRole {
	if x != nil {
		return x.Result
	}
	return nil
}

// 团队角色数据
type OrgRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId   int64       `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName string      `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	PermList []*RolePerm `protobuf:"bytes,3,rep,name=permList,proto3" json:"permList,omitempty"`
	ShopList []*RoleShop `protobuf:"bytes,4,rep,name=shopList,proto3" json:"shopList,omitempty"`
	UserList []*RoleUser `protobuf:"bytes,5,rep,name=userList,proto3" json:"userList,omitempty"`
}

func (x *OrgRole) Reset() {
	*x = OrgRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgRole) ProtoMessage() {}

func (x *OrgRole) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgRole.ProtoReflect.Descriptor instead.
func (*OrgRole) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{16}
}

func (x *OrgRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *OrgRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *OrgRole) GetPermList() []*RolePerm {
	if x != nil {
		return x.PermList
	}
	return nil
}

func (x *OrgRole) GetShopList() []*RoleShop {
	if x != nil {
		return x.ShopList
	}
	return nil
}

func (x *OrgRole) GetUserList() []*RoleUser {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 角色权限数据
type RolePerm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermId   int64  `protobuf:"varint,1,opt,name=permId,proto3" json:"permId,omitempty"`
	PermName string `protobuf:"bytes,2,opt,name=permName,proto3" json:"permName,omitempty"`
	PermCode string `protobuf:"bytes,3,opt,name=permCode,proto3" json:"permCode,omitempty"`
}

func (x *RolePerm) Reset() {
	*x = RolePerm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePerm) ProtoMessage() {}

func (x *RolePerm) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePerm.ProtoReflect.Descriptor instead.
func (*RolePerm) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{17}
}

func (x *RolePerm) GetPermId() int64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *RolePerm) GetPermName() string {
	if x != nil {
		return x.PermName
	}
	return ""
}

func (x *RolePerm) GetPermCode() string {
	if x != nil {
		return x.PermCode
	}
	return ""
}

// 角色店铺数据
type RoleShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId       int64  `protobuf:"varint,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	ShopName     string `protobuf:"bytes,2,opt,name=shopName,proto3" json:"shopName,omitempty"`
	PlatformType int64  `protobuf:"varint,3,opt,name=PlatformType,proto3" json:"PlatformType,omitempty"`
}

func (x *RoleShop) Reset() {
	*x = RoleShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleShop) ProtoMessage() {}

func (x *RoleShop) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleShop.ProtoReflect.Descriptor instead.
func (*RoleShop) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{18}
}

func (x *RoleShop) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *RoleShop) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *RoleShop) GetPlatformType() int64 {
	if x != nil {
		return x.PlatformType
	}
	return 0
}

// 角色用户数据
type RoleUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImg  string `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
}

func (x *RoleUser) Reset() {
	*x = RoleUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUser) ProtoMessage() {}

func (x *RoleUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUser.ProtoReflect.Descriptor instead.
func (*RoleUser) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{19}
}

func (x *RoleUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoleUser) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *RoleUser) GetHeadImg() string {
	if x != nil {
		return x.HeadImg
	}
	return ""
}

// 获取团队权限列表请求体
type OrgPermListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *OrgPermListReq) Reset() {
	*x = OrgPermListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgPermListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgPermListReq) ProtoMessage() {}

func (x *OrgPermListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgPermListReq.ProtoReflect.Descriptor instead.
func (*OrgPermListReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{20}
}

func (x *OrgPermListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取团队权限列表返回体
type OrgPermListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result []*OrgPerm `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *OrgPermListResp) Reset() {
	*x = OrgPermListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgPermListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgPermListResp) ProtoMessage() {}

func (x *OrgPermListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgPermListResp.ProtoReflect.Descriptor instead.
func (*OrgPermListResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{21}
}

func (x *OrgPermListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrgPermListResp) GetResult() []*OrgPerm {
	if x != nil {
		return x.Result
	}
	return nil
}

// 团队权限数据
type OrgPerm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermId   int64  `protobuf:"varint,1,opt,name=permId,proto3" json:"permId,omitempty"`
	PermName string `protobuf:"bytes,2,opt,name=permName,proto3" json:"permName,omitempty"`
	PermCode string `protobuf:"bytes,3,opt,name=permCode,proto3" json:"permCode,omitempty"`
	ParentId int64  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Sort     int64  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *OrgPerm) Reset() {
	*x = OrgPerm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgPerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgPerm) ProtoMessage() {}

func (x *OrgPerm) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgPerm.ProtoReflect.Descriptor instead.
func (*OrgPerm) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{22}
}

func (x *OrgPerm) GetPermId() int64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *OrgPerm) GetPermName() string {
	if x != nil {
		return x.PermName
	}
	return ""
}

func (x *OrgPerm) GetPermCode() string {
	if x != nil {
		return x.PermCode
	}
	return ""
}

func (x *OrgPerm) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *OrgPerm) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 创建角色请求体
type CreateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoleName   string  `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	PermIdList []int64 `protobuf:"varint,3,rep,packed,name=permIdList,proto3" json:"permIdList,omitempty"`
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{23}
}

func (x *CreateRoleReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CreateRoleReq) GetPermIdList() []int64 {
	if x != nil {
		return x.PermIdList
	}
	return nil
}

// 创建角色返回体
type CreateRoleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CreateRoleResp) Reset() {
	*x = CreateRoleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResp) ProtoMessage() {}

func (x *CreateRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResp.ProtoReflect.Descriptor instead.
func (*CreateRoleResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{24}
}

func (x *CreateRoleResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 更新角色请求体
type UpdateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoleId     int64   `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName   string  `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName,omitempty"`
	PermIdList []int64 `protobuf:"varint,4,rep,packed,name=permIdList,proto3" json:"permIdList,omitempty"`
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateRoleReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateRoleReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UpdateRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UpdateRoleReq) GetPermIdList() []int64 {
	if x != nil {
		return x.PermIdList
	}
	return nil
}

// 更新角色返回体
type UpdateRoleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UpdateRoleResp) Reset() {
	*x = UpdateRoleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_org_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResp) ProtoMessage() {}

func (x *UpdateRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_org_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResp.ProtoReflect.Descriptor instead.
func (*UpdateRoleResp) Descriptor() ([]byte, []int) {
	return file_pb_org_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateRoleResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_pb_org_proto protoreflect.FileDescriptor

var file_pb_org_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x53, 0x0a, 0x10, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4f, 0x72, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x3f, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x67, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x25, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x52, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3e, 0x0a, 0x0e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x10,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x4e, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f,
	0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f,
	0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4c, 0x0a,
	0x14, 0x41, 0x67, 0x72, 0x65, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f,
	0x72, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x41,
	0x67, 0x72, 0x65, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4d, 0x0a, 0x15, 0x41, 0x67, 0x72, 0x65,
	0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x16, 0x41, 0x67, 0x72, 0x65, 0x65,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x4f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x4c, 0x0a, 0x0f, 0x4f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0xc1, 0x01, 0x0a, 0x07, 0x4f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x68, 0x6f,
	0x70, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x50,
	0x65, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x65, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x65, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x6d, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x72, 0x6d, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x62, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x58, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x49,
	0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6d,
	0x67, 0x22, 0x28, 0x0a, 0x0e, 0x4f, 0x72, 0x67, 0x50, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x0f, 0x4f,
	0x72, 0x67, 0x50, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x67, 0x50, 0x65, 0x72,
	0x6d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x89, 0x01, 0x0a, 0x07, 0x4f, 0x72,
	0x67, 0x50, 0x65, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x65, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x65, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72,
	0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x72,
	0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x63, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65,
	0x72, 0x6d, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a,
	0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x7b, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x24, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0x87, 0x05, 0x0a, 0x03, 0x4f, 0x72, 0x67, 0x12, 0x37, 0x0a, 0x09, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x12, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a,
	0x0c, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x12, 0x15, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x0d,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x12, 0x16, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f,
	0x72, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4c,
	0x0a, 0x11, 0x61, 0x67, 0x72, 0x65, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e,
	0x4f, 0x72, 0x67, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x72, 0x65, 0x65,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x72, 0x65, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x12,
	0x61, 0x67, 0x72, 0x65, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f,
	0x72, 0x67, 0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x72, 0x65, 0x65, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x72, 0x65, 0x65, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a,
	0x0e, 0x67, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x67,
	0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0e,
	0x67, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x50, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x67, 0x50, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x67, 0x50,
	0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_org_proto_rawDescOnce sync.Once
	file_pb_org_proto_rawDescData = file_pb_org_proto_rawDesc
)

func file_pb_org_proto_rawDescGZIP() []byte {
	file_pb_org_proto_rawDescOnce.Do(func() {
		file_pb_org_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_org_proto_rawDescData)
	})
	return file_pb_org_proto_rawDescData
}

var file_pb_org_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pb_org_proto_goTypes = []any{
	(*SearchOrgReq)(nil),           // 0: user.SearchOrgReq
	(*SearchOrgReqResp)(nil),       // 1: user.SearchOrgReqResp
	(*SearchOrgInfo)(nil),          // 2: user.SearchOrgInfo
	(*SearchUserReq)(nil),          // 3: user.SearchUserReq
	(*SearchUserResp)(nil),         // 4: user.SearchUserResp
	(*SearchUserInfo)(nil),         // 5: user.SearchUserInfo
	(*ApplyJoinOrgReq)(nil),        // 6: user.ApplyJoinOrgReq
	(*ApplyJoinOrgResp)(nil),       // 7: user.ApplyJoinOrgResp
	(*InviteJoinOrgReq)(nil),       // 8: user.InviteJoinOrgReq
	(*InviteJoinOrgResp)(nil),      // 9: user.InviteJoinOrgResp
	(*AgreeApplyJoinOrgReq)(nil),   // 10: user.AgreeApplyJoinOrgReq
	(*AgreeApplyJoinOrgResp)(nil),  // 11: user.AgreeApplyJoinOrgResp
	(*AgreeInviteJoinOrgReq)(nil),  // 12: user.AgreeInviteJoinOrgReq
	(*AgreeInviteJoinOrgResp)(nil), // 13: user.AgreeInviteJoinOrgResp
	(*OrgRoleListReq)(nil),         // 14: user.OrgRoleListReq
	(*OrgRoleListResp)(nil),        // 15: user.OrgRoleListResp
	(*OrgRole)(nil),                // 16: user.OrgRole
	(*RolePerm)(nil),               // 17: user.RolePerm
	(*RoleShop)(nil),               // 18: user.RoleShop
	(*RoleUser)(nil),               // 19: user.RoleUser
	(*OrgPermListReq)(nil),         // 20: user.OrgPermListReq
	(*OrgPermListResp)(nil),        // 21: user.OrgPermListResp
	(*OrgPerm)(nil),                // 22: user.OrgPerm
	(*CreateRoleReq)(nil),          // 23: user.CreateRoleReq
	(*CreateRoleResp)(nil),         // 24: user.CreateRoleResp
	(*UpdateRoleReq)(nil),          // 25: user.UpdateRoleReq
	(*UpdateRoleResp)(nil),         // 26: user.UpdateRoleResp
}
var file_pb_org_proto_depIdxs = []int32{
	2,  // 0: user.SearchOrgReqResp.result:type_name -> user.SearchOrgInfo
	5,  // 1: user.SearchUserResp.result:type_name -> user.SearchUserInfo
	16, // 2: user.OrgRoleListResp.result:type_name -> user.OrgRole
	17, // 3: user.OrgRole.permList:type_name -> user.RolePerm
	18, // 4: user.OrgRole.shopList:type_name -> user.RoleShop
	19, // 5: user.OrgRole.userList:type_name -> user.RoleUser
	22, // 6: user.OrgPermListResp.result:type_name -> user.OrgPerm
	0,  // 7: user.Org.searchOrg:input_type -> user.SearchOrgReq
	3,  // 8: user.Org.searchUser:input_type -> user.SearchUserReq
	6,  // 9: user.Org.applyJoinOrg:input_type -> user.ApplyJoinOrgReq
	8,  // 10: user.Org.inviteJoinOrg:input_type -> user.InviteJoinOrgReq
	10, // 11: user.Org.agreeApplyJoinOrg:input_type -> user.AgreeApplyJoinOrgReq
	12, // 12: user.Org.agreeInviteJoinOrg:input_type -> user.AgreeInviteJoinOrgReq
	14, // 13: user.Org.getOrgRoleList:input_type -> user.OrgRoleListReq
	20, // 14: user.Org.getOrgPermList:input_type -> user.OrgPermListReq
	23, // 15: user.Org.createRole:input_type -> user.CreateRoleReq
	25, // 16: user.Org.updateRole:input_type -> user.UpdateRoleReq
	1,  // 17: user.Org.searchOrg:output_type -> user.SearchOrgReqResp
	4,  // 18: user.Org.searchUser:output_type -> user.SearchUserResp
	7,  // 19: user.Org.applyJoinOrg:output_type -> user.ApplyJoinOrgResp
	9,  // 20: user.Org.inviteJoinOrg:output_type -> user.InviteJoinOrgResp
	11, // 21: user.Org.agreeApplyJoinOrg:output_type -> user.AgreeApplyJoinOrgResp
	13, // 22: user.Org.agreeInviteJoinOrg:output_type -> user.AgreeInviteJoinOrgResp
	15, // 23: user.Org.getOrgRoleList:output_type -> user.OrgRoleListResp
	21, // 24: user.Org.getOrgPermList:output_type -> user.OrgPermListResp
	24, // 25: user.Org.createRole:output_type -> user.CreateRoleResp
	26, // 26: user.Org.updateRole:output_type -> user.UpdateRoleResp
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_org_proto_init() }
func file_pb_org_proto_init() {
	if File_pb_org_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_org_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchOrgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearchOrgReqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SearchOrgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyJoinOrgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyJoinOrgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*InviteJoinOrgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*InviteJoinOrgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*AgreeApplyJoinOrgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*AgreeApplyJoinOrgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AgreeInviteJoinOrgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AgreeInviteJoinOrgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*OrgRoleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*OrgRoleListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*OrgRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*RolePerm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*RoleShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*RoleUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*OrgPermListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*OrgPermListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*OrgPerm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_org_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateRoleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_org_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_org_proto_goTypes,
		DependencyIndexes: file_pb_org_proto_depIdxs,
		MessageInfos:      file_pb_org_proto_msgTypes,
	}.Build()
	File_pb_org_proto = out.File
	file_pb_org_proto_rawDesc = nil
	file_pb_org_proto_goTypes = nil
	file_pb_org_proto_depIdxs = nil
}
