// Code generated by goctl. DO NOT EDIT.
// Source: training.proto

package basicfunction

import (
	"context"

	"yufuture-gpt/app/training/cmd/rpc/pb/training"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGoodsReq                  = training.AddGoodsReq
	AddGoodsResp                 = training.AddGoodsResp
	CancelPreSettingGoodsReq     = training.CancelPreSettingGoodsReq
	CancelPreSettingGoodsResp    = training.CancelPreSettingGoodsResp
	CancelPreSettingReq          = training.CancelPreSettingReq
	DictInfo                     = training.DictInfo
	DictInfoByTypeReq            = training.DictInfoByTypeReq
	DictInfoByTypeResp           = training.DictInfoByTypeResp
	GetGoodsTrainingProgressReq  = training.GetGoodsTrainingProgressReq
	GetGoodsTrainingProgressResp = training.GetGoodsTrainingProgressResp
	GetGoodsTrainingResultReq    = training.GetGoodsTrainingResultReq
	GetGoodsTrainingResultResp   = training.GetGoodsTrainingResultResp
	GetShopTrainingProgressReq   = training.GetShopTrainingProgressReq
	GetShopTrainingProgressResp  = training.GetShopTrainingProgressResp
	GoodsPageListReq             = training.GoodsPageListReq
	GoodsPageListResp            = training.GoodsPageListResp
	GoodsResp                    = training.GoodsResp
	GoodsTrainingReq             = training.GoodsTrainingReq
	GoodsTrainingResp            = training.GoodsTrainingResp
	JudgeShopFirstReq            = training.JudgeShopFirstReq
	JudgeShopFirstResp           = training.JudgeShopFirstResp
	KnowledgeBaseTrainingReq     = training.KnowledgeBaseTrainingReq
	KnowledgeBaseTrainingResp    = training.KnowledgeBaseTrainingResp
	PreSettingGoodsReq           = training.PreSettingGoodsReq
	PreSettingGoodsResp          = training.PreSettingGoodsResp
	SaveGoods                    = training.SaveGoods
	SaveShopReq                  = training.SaveShopReq
	SaveShopResp                 = training.SaveShopResp
	ShopPageListReq              = training.ShopPageListReq
	ShopPageListResp             = training.ShopPageListResp
	ShopResp                     = training.ShopResp
	ShopTrainingReq              = training.ShopTrainingReq
	ShopTrainingResp             = training.ShopTrainingResp
	TrainingGoodsReq             = training.TrainingGoodsReq
	TrainingGoodsResp            = training.TrainingGoodsResp
	TrainingShopReq              = training.TrainingShopReq
	TrainingShopResp             = training.TrainingShopResp

	BasicFunction interface {
		GetDictInfoByType(ctx context.Context, in *DictInfoByTypeReq, opts ...grpc.CallOption) (*DictInfoByTypeResp, error)
	}

	defaultBasicFunction struct {
		cli zrpc.Client
	}
)

func NewBasicFunction(cli zrpc.Client) BasicFunction {
	return &defaultBasicFunction{
		cli: cli,
	}
}

func (m *defaultBasicFunction) GetDictInfoByType(ctx context.Context, in *DictInfoByTypeReq, opts ...grpc.CallOption) (*DictInfoByTypeResp, error) {
	client := training.NewBasicFunctionClient(m.cli.Conn())
	return client.GetDictInfoByType(ctx, in, opts...)
}
